version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_django_01_network
    volumes:
      - gis_django_01_static:/data/static/
      - gis_django_01_media:/data/media/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django:
    image: gis_django_01:4
    networks:
      - gis_django_01_network
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - gis_django_01_static:/home/JH/staticfiles/
      - gis_django_01_media:/home/JH/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_django_01_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: admin1234
      MARIADB_ROOT_PASSWORD: admin1234


networks:
  gis_django_01_network:

volumes:
  gis_django_01_static:
  gis_django_01_media:
  gis_mariadb:

secrets:
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  DJANGO_SECRET_KEY:
    external: true